FROM ubuntu:noble

ENV LANG=en_US.utf8  LC_ALL=en_US.utf8
ENV TZ=Europe/London
RUN echo "Europe/London" > /etc/timezone

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    automake \
    ca-certificates \
    cmake \
    curl \
    git \
    gnupg \
    less \
    locales \
    neovim \
    ninja-build \
    patch \
    pkg-config \
    qemu-user-static \
    qemu-utils \
    tar \
    tzdata \
    unzip \
    wget \
    zip \
    zsh && \
    chsh --shell /bin/zsh

RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 && \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

RUN apt autoclean && apt autoremove --yes

# RUN cd ~ && git clone https://github.com/jart/cosmopolitan.git --single-branch --no-tags --depth=1 && \
# run setup & tool/cosmocc/package.sh Cosmocc

# RUN cd /usr/local/bin/ && \
#     # These utilities are not included in Cosmopolitan bootstrap
#     wget -nv --limit-rate=1m https://cosmo.zip/pub/cosmos/bin/brotli && \
#     wget -nv --limit-rate=1m https://cosmo.zip/pub/cosmos/bin/gmake && \
#     wget -nv --limit-rate=1m https://cosmo.zip/pub/cosmos/bin/grep  && \
#     wget -nv --limit-rate=1m https://cosmo.zip/pub/cosmos/bin/install && \
#     wget -nv --limit-rate=1m https://cosmo.zip/pub/cosmos/bin/less && \
#     wget -nv --limit-rate=1m https://cosmo.zip/pub/cosmos/bin/tar && \
#     wget -nv --limit-rate=1m https://cosmo.zip/pub/cosmos/bin/tree && \
#     wget -nv --limit-rate=1m https://cosmo.zip/pub/cosmos/bin/unzip && \
#     wget -nv --limit-rate=1m https://cosmo.zip/pub/cosmos/bin/zip && \
#     chmod +x /usr/local/bin/*

RUN curl -fsSL https://bun.sh/install | bash

WORKDIR "/root/"

ENTRYPOINT ["zsh"]
